### ISSUE TITLE
Clean up overall logging management

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-aws-stack-builder#12]
All log files across all components need to be configured with CloudWatch.

All log files should also have a log rotation mechanism, this will differ between applications. Some applications might already have a built-in log rotation logic, where others need logrotate to be set up via Puppet.

**Comment by cliffano** [comment]
CloudWatch agent needs to be baked in packer-aem, it should follow a similar pattern like SSM agent with enable/disable flag.

The provisioning for each component in aem-aws-stack-provisioner should then add CW logs configuration file, listing all log files that the platform produces.

**Comment by ovlords** [comment]
enable/disable flag for installing CW agent added. 993785e

**Comment by ovlords** [comment]
See feature/cloudwatchlogs_reorg

**Comment by mbloch1986** [comment]
* Moving Puppet Stack init & scheduled job logfiles to /var/log/shinesolutions introduced in AEM AWS Stack Provisioner version 2.5.0

* Add feature to configure logrotation in AEM AWS Stack Builder introduced in version 2.2.0

* Add feature to configure logrotation in Puppet AEM Curator version 0.10.0 & in AEM AWS Stack Provisioner version 2.5.0
