### ISSUE TITLE
Clean up Simian Army's SimpleDB domain as part of stack deletion

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-aws-stack-builder#19]
Simian Army installation creates a SimpleDB domain which is not associated to CloudFormation stack.
Stack deletion should also delete this SimpleDB domain in ChaosMonkey playbook https://github.com/shinesolutions/aem-aws-stack-builder/blob/master/ansible/playbooks/apps/chaos-monkey.yaml .

**Comment by Epoxboy** [comment]
I've added a new task in playbook main.yaml(PR #85 ) for calling a new module delete_sdb_domain.py (PR #86 ) for adding this new feature. It's been tested and all good to go!

Thank you for the help in assisting me to get familiar with this project and correct my Python code! ; )
