### ISSUE TITLE
Introduce data device name configuration property

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-aws-stack-builder#203]
Currently data device name is defaulted to `/dev/sdb` , while the root device name is parameterised as `ami_root_device_name = /dev/sda1` .

In order to support other AMIs/OSes with non default data device name, we need to make it configurable via property `ami_data_device_name` .

**Comment by michaeldiender-shinesolutions** [comment]
https://github.com/shinesolutions/aem-aws-stack-builder/pull/237
