### ISSUE TITLE
Update Encryption and Cipher Suite for SSL on load balancers.

### ISSUE THREAD

**Issue by nerdy-dav** [shinesolutions/aem-aws-stack-builder#204]
Default SSL settings on ELB's are not sufficient for some clients. Some ciphers and encryption methods that have known issues are still used. Further details will be added at a later date concerning the best cipher methods.

**Comment by dav-shine** [comment]
PR Created.

Solution: Is to make a parameter for the Cipher Suite. This gets added to the cloud-formation during the build.

**Comment by mbloch1986** [comment]
inluded in release `3.4.0`
