### ISSUE TITLE
Introduce CloudWatch Alarm to monitor Stack manager Lambda function errors

### ISSUE THREAD

**Issue by mbloch1986** [shinesolutions/aem-aws-stack-builder#210]
We need to introduce a flag which enable/disable the creation of a CloudWatch alarm which monitors if a Stack Manager Lambda function (offline-snapshot/stack-manager/purge_snapshot) fails and notify the user if required.

**Comment by ovlords** [comment]
Name: APP-SM-AemSnapshotsPurgefailure
Metric: APP-SM-AemSnapshotsPurgefailure

>= 0.5 for 1 datapoints within 5 minutes

 

Name: APP-SM-AemOfflineBackupfailure
Metric: APP-SM-AemOfflineBackupfailure

>= 0.5 for 1 datapoints within 5 minutes

**Comment by ovlords** [comment]
This might not necessarily need to be a CW alarm, just need notification when there are errors.

**Comment by ovlords** [comment]
TODO: (Get List of Alarms)

**Comment by mbloch1986** [comment]
Inlcuded in AEM OpenCloud version 4.0.0
