### ISSUE TITLE
Intermittent JMX port binding error

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-aws-stack-builder#213]
There's a rare scenario where the default JMX port (59182 for AEM Author and 59183 for AEM Publish) conflicts with dynamic ports usage.
In order to remove this probability, change the defaults to unassigned 5982 and 5983 https://www.speedguide.net/port.php?port=5982 https://www.speedguide.net/port.php?port=5983

```
Error: Exception thrown by the agent : java.rmi.server.ExportException: Port already in use: 59182; nested exception is: 
    java.net.BindException: Address already in use (Bind failed)
```

**Comment by mbloch1986** [comment]
Defaults were updated with AEM-AWS-Stack-Builder release `3.2.1`
