### ISSUE TITLE
AEM proxy provisioning

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-aws-stack-builder#235]
User configuration currently allows proxy details, however, it's set only at the OS layer and not yet at AEM layer.

This needs to be added to AEM provisioning in a way that the proxy details is set as AEM's configuration. That way all applications running on AEM will automatically use the proxy for outbound connection.

**Comment by mbloch1986** [comment]
included in the releases

aem-aws-stack-builder 3.4.0
aem-aws-stack-provisioner 3.4.0
puppet-aem-curator 1.5.0
ruby_aem 2.4.0
