### ISSUE TITLE
author standby role needs putmetricdata action permission

### ISSUE THREAD

**Issue by michaeldiender-shinesolutions** [shinesolutions/aem-aws-stack-builder#24]
author standby role needs putmetricdata action permission. consider adding to all roles.

 403 Client Error: Forbidden for url: https://monitoring.ap-southeast-2.amazonaws.com/?Action=PutMetricData&MetricData.member.

used for putting the sync delay metric

**Comment by jimmyting44** [comment]
"Author" role already has been given the [cloudwatch:PutMetricData](https://github.com/shinesolutions/aem-aws-stack-builder/blob/master/cloudformation/apps/full-set/instance-profiles.yaml#L144) permission.
