### ISSUE TITLE
provisioning script fails if pre-common script included in custom provisioning

### ISSUE THREAD

**Issue by stanley-zhang** [shinesolutions/aem-aws-stack-builder#257]
At line 53 of aem-aws-stack-builder/scripts/stack-init.sh, if we are running a pre-common script it will cause the script to exit, because we are changing to the custom provisioner directory as part of the run custom stage function.

Can resolve by changing back to the provisioning directory after running script or not changing directory to run the script

**Comment by mbloch1986** [comment]
Included in AEM-AWS-Stack-Builder release 3.6.0
