### ISSUE TITLE
Scaling policies when instances have high cpu usage.

### ISSUE THREAD

**Issue by michaeldiender-shinesolutions** [shinesolutions/aem-aws-stack-builder#26]
As the first line of defence, dispatcher sitting in front of publisher must be able to scale horizontally when under heavy load. Even though the architecture might include a CDN in front of the dispatcher, we need to consider the scenario when the CDN is not inside AWS and hence there would be a disaster scenario when that external CDN is unavailable.

**Comment by cliffano** [comment]
Since Dave already created PR #37 for `release/1` branch, @mbloch1986 will now retrofit the PR to `master` branch for v2.

**Comment by cliffano** [comment]
Closing this issue since the scaling policy has been retrofitted to v2.x as part of PR #58, and will be included in v2.1.0 .
Unfortunately PR #37 will have to be closed off without merge for now since all users agree on upgrading to v2.x instead.
