### ISSUE TITLE
Add a CloudWatch Alarm when AuthorLoadBalancer number if instances in-service is > 1.

### ISSUE THREAD

**Issue by irgeek** [shinesolutions/aem-aws-stack-builder#28]
If both author instances come into service at the same time, we'll be in a world of hurt. We should add an alarm that triggers if there's more than one author in-service.

**Comment by SregorT** [comment]
The requested alarm is in place in the author.yaml configuration script.

It is called MultiAuthorInstanceAlarm

**Comment by cliffano** [comment]
Alarm action has been fixed in https://github.com/shinesolutions/aem-aws-stack-builder/pull/84/files, email notification added to https://github.com/shinesolutions/aem-aws-stack-builder/pull/87 .
