### ISSUE TITLE
Cloudformation templates uploaded into S3 and ACL set to public-read, this can breach security policies

### ISSUE THREAD

**Issue by engshine** [shinesolutions/aem-aws-stack-builder#292]
Cloudformation templates are uploaded into S3 and the ACLs set to 'public-read'.
This is not required (any more?) for the stack to successfully launch.

Setting objects to public-read should only be applied to objects that require it.

**Comment by engshine** [comment]
PR for the fix:
https://github.com/shinesolutions/aem-aws-stack-builder/pull/293/

**Comment by mbloch1986** [comment]
Included in aem-aws-stack-builder release 4.0.0.
