### ISSUE TITLE
Configurable AZs via inventory file

### ISSUE THREAD

**Issue by michaeldiender-shinesolutions** [shinesolutions/aem-aws-stack-builder#30]
templates currently support 2 AZ and 2 Subnet. would be nice to have templates to create a 3 AZ 3 Subnet network

**Comment by michaeldiender-shinesolutions** [comment]
see feature/3AZ_network branch for example.

**Comment by cliffano** [comment]
This feature was already added to release/1, but unfortunately was lost in release/2 (aka dev branch). The ability to specify configurable number of AZs needs to be resurrected in master branch.

**Comment by cliffano** [comment]
Here's the commit that turned AZ-specific variables into lists https://github.com/shinesolutions/aem-aws-stack-builder/commit/97219f304a7a96b1a9704176ab60651cc5e64132

**Comment by cliffano** [comment]
The status for v2 is that this is no longer configurable via the main application's Ansible config as in v1.
However, this feature is still available via either of the following:
A. VPC stack's output parameters with comma-separated values for the subnets
B. `network-exports` configuration file to be used to provision network-exports stack's output parameters with the same format as above

This means v2 still provides the ability to have a dynamic list of subnets, the change is that subnet lists are now consumed via stack outputs to be imported by the consolidated and full-set architecture stacks.
