### ISSUE TITLE
Add DNS to author-publish-dispatcher CF

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-aws-stack-builder#38]
author-publish-dispatcher component CF is currently missing a Route53 record.
Keep the naming convention consistent with the other components.

**Comment by ovlords** [comment]
Added a DNS A Record to author-publish-dispatcher CF.

**Comment by cliffano** [comment]
Please have a look at the commit review https://github.com/shinesolutions/aem-aws-stack-builder/commit/427d296f2b084f8f9fc8612f36e7f005b4be40c2 .

**Comment by ovlords** [comment]
As requested in commit review https://github.com/shinesolutions/aem-aws-stack-builder/commit/427d296f2b084f8f9fc8612f36e7f005b4be40c2, introduced variables to replace hardcoded values.

**Comment by cliffano** [comment]
LGTM. author-publish-dispatcher params are now configurable in inventory file.
