### ISSUE TITLE
Change CPU Utilization Alarm Metric Statistics

### ISSUE THREAD

**Issue by hoomaan-kh** [shinesolutions/aem-aws-stack-builder#398]
**Is your feature request related to a problem? Please describe.**
CPU  Utilisation alarms are defined based on Average CPU usage of instances within AutoScaling Group, in this case if one instance has CPU higher Utilisation problem it may not be detected(or delayed) using average metrics.

**Describe the solution you'd like**
Actually CPU Utilization alarm is based on average CPU Utilisation. so We need to change is to change this  Metric type to maximum.

**Describe alternatives you've considered**
N/A

**Additional context**
N/a

**Comment by mbloch1986** [comment]
Improvement included in aem-aws-stack-builder release 4.40.0
