### ISSUE TITLE
Change default value of ttl in switch-dns

### ISSUE THREAD

**Issue by hoomaan-kh** [shinesolutions/aem-aws-stack-builder#411]
**Is your feature request related to a problem? 
Switch-DNS function is used to modify route53 but ttl default value is not configurable,  we need a function to have predefined ttl values.

**Describe the solution you'd like**
add configurable value to be used when switching DNS

**Describe alternatives you've considered**
we can manually change ttl value after switching the DNS 

**Additional context**
N/A

**Comment by mbloch1986** [comment]
Feature is included in release 4.41.0.
