### ISSUE TITLE
Add support for AEM 6.3

### ISSUE THREAD

**Issue by wyvern8** [shinesolutions/aem-aws-stack-builder#42]
Planning upgrades for a number of stacks, and will need support for latest versions.

**Comment by cliffano** [comment]
AEM 6.3 SP1 Puppet provisioner is available on aem_curator https://github.com/shinesolutions/puppet-aem-curator/blob/master/manifests/install_aem63_sp1.pp .

**Comment by cliffano** [comment]
Author Standby package change in 6.3 has been implemented in aem_resources https://github.com/shinesolutions/puppet-aem-resources/issues/22

AEM 6.3 SP1 CFP2 Puppet provisioner is now available on aem_curator https://github.com/shinesolutions/puppet-aem-curator/issues/6

**Comment by wyvern8** [comment]
looks like we are kicking upgrades off next week, so great to see progress.

**Comment by cliffano** [comment]
Closing this ticket since AEM 6.3 support has been available since version 2.1.0 .
