### ISSUE TITLE
CloudWatch dashboard load balancer and  healthy/unhealthy hosts metrics are missing

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-aws-stack-builder#433]
**Describe the bug**
CloudWatch dashboard has a section showing how many instances are up and running from each auto-scaling group (Author-Dispatcher, Publish, Publish-Dispatcher, etc), and also some counts related to load balancers. Those metrics are no longer displayed since classic load balancers were replaced with application load balancers.

**To Reproduce**
1. Create a new AEM full-set environment
2. View the CloudWatch dashboard
3. The metrics are not showing up

**Expected behavior**
The metrics should show up, showing how many instances are up and running on each of those groups. The counts with various load balancer stats should also show up.

**Comment by PradKhandelwal** [comment]
[CloudWatchDashboardUpdate.pdf](https://github.com/shinesolutions/aem-aws-stack-builder/files/6996063/CloudWatchDashboardUpdate.pdf)

**Comment by PradKhandelwal** [comment]
Exported the Values of the Target Group corresponding to the Author, Author Dispatcher and Publish Dispatcher.
Made changes to the files author.yaml, author-dispatcher.yaml and publish-dispatcher.yaml.

Making changes to the monitoring.yaml, to import the vlaues and editing the definations of the metrics.
