### ISSUE TITLE
Introduce Stack Manager CloudFormation template

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-aws-stack-builder#62]
The current CloudFormation template (along with config and playbooks) need to be added to aem-aws-stack-builder. This is mostly a migration effort from Stack Manager Cloud repo which currently contains the CF template(s).

This is an effort to simplify user's stack building configuration and provisioning.
At the same time, it's also an effort to make things consistent that the application repos (stack manager, orchestrator, etc) produces the application code, while AWS CloudFormation templates live in aem-aws-stack-builder.

**Comment by mbloch1986** [comment]
Done and merged:

https://github.com/shinesolutions/aem-aws-stack-builder/commit/855a9049540bd1eafe52e5bd514b2e1d9fd85296
