### ISSUE TITLE
Create CloudWatch alarm for messaging queue size

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-aws-stack-builder#70]
Messaging stack contains an SQS queue for handling ASG events, which could potentially flood when the stack keeps recovering/scaling (ASG keeps terminating and launching instances) in a cycle, e.g. due to provisioning failure caused by failing outbound proxy.

Need to create a CloudWatch alarm on the messaging stack to accompany the SQS queue, set the condition to 'when there are 10 or more messages in the queue'.

**Comment by SregorT** [comment]
Note that "payload size" != "queue size" :-)

**Comment by cliffano** [comment]
Cheers :). Updated the title.

**Comment by cliffano** [comment]
Done. To be included in v2.1.0 .
