### ISSUE TITLE
SNS Topic ARN integration in AEM Full-Set prerequisites

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-aws-stack-builder#83]
AEM Full-Set currently has a CloudWatch alarm but it's not subscribed to any SNS topic yet.
An SNS topic ARN needs to be added to the current Full-Set prerequisites stack, and produced as output parameter. The main stack should then simply import this ARN.
The ARN should be configured following the pattern of network-exports.

If other users need a custom SNS Topic to be created as part of prerequisites, then it's time to introduce a new prerequisites stack. But that's not in scope of the current prerequisites.

**Comment by mbloch1986** [comment]
Creation of an Alarm SNS Topic is already implemented ... see Ansible playbook messaging.yaml in the full-set.

**Comment by mbloch1986** [comment]
Done.
