### ISSUE TITLE
Set Proxy configuration for SSM Agent Service

### ISSUE THREAD

**Issue by mbloch1986** [shinesolutions/aem-aws-stack-builder#99]
In order to let the running SSM Agent daemon on linux contact the AWS API behind a proxy server, we need to add a Manifest which configured the proxy setting for the SSM Agent Daemon.

As described here:

https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-proxy-with-ssm-agent.html

The first test shows, that the configuration file for systemd seems to be the best solution.

**Comment by ovlords** [comment]
This issue has been re-created in packer-aem as this is where fix should be done.

https://github.com/shinesolutions/packer-aem/issues/64
